"""
End-to-end (API-level) walk of the candidate-facing inbound core loop, guarding the
P1 fixes: status_token auto-generation, status portal timeline + pre_eval_token, and
the pre-evaluation GET/submit endpoints. Deterministic — runs against the test
container, no browser/LLM needed. If any of these silently break again, this fails.
"""
import json
import uuid

import pytest
import pytest_asyncio



@pytest_asyncio.fixture
async def seeded_app(db_pool):
    """Seed org → dept → candidate → position → application. status_token is NOT
    set explicitly, so it must come from the column DEFAULT (the P1-8 fix)."""
    sfx = uuid.uuid4().hex[:8]
    async with db_pool.acquire() as conn:
        org = await conn.fetchval(
            "INSERT INTO organizations (name,slug,segment,size) "
            "VALUES ($1,$2,'tech','small') RETURNING id",
            f"Loop Org {sfx}", f"loop-org-{sfx}",
        )
        dept = await conn.fetchval(
            "INSERT INTO departments (org_id,name) VALUES ($1,'Eng') RETURNING id", org
        )
        cand = await conn.fetchval(
            "INSERT INTO candidates (org_id,name,email) VALUES ($1,'Ada Lovelace','ada@example.com') RETURNING id",
            org,
        )
        pos = await conn.fetchval(
            "INSERT INTO positions (org_id,department_id,role_name,status) "
            "VALUES ($1,$2,'Backend Engineer','open') RETURNING id",
            org, dept,
        )
        app_row = await conn.fetchrow(
            "INSERT INTO candidate_applications (candidate_id,position_id,org_id,department_id,status) "
            "VALUES ($1,$2,$3,$4,'applied') RETURNING id, status_token",
            cand, pos, org, dept,
        )
        await conn.execute(
            "INSERT INTO pipeline_events (org_id,candidate_id,position_id,application_id,event_type) "
            "VALUES ($1,$2,$3,$4,'application_received')",
            org, cand, pos, app_row["id"],
        )
        
    yield {
        "org": org, "dept": dept, "candidate": cand, "position": pos,
        "app_id": app_row["id"], "status_token": app_row["status_token"],
    }
    
    # Clean up in FK dependency order (organizations isn't ON DELETE CASCADE
    # from candidate_applications/pipeline_events, so delete children first).
    async with db_pool.acquire() as conn:
        for tbl in ("pre_evaluations", "pipeline_events", "candidate_applications",
                    "candidates", "positions", "departments", "organizations"):
            col = "id" if tbl == "organizations" else "org_id"
            try:
                await conn.execute(f"DELETE FROM {tbl} WHERE {col}=$1", org)
            except Exception:
                pass


@pytest.mark.asyncio
async def test_status_token_is_autogenerated(seeded_app):
    """P1-8: new applications must get a status_token from the column DEFAULT,
    otherwise the public status portal 404s for every fresh applicant."""
    assert seeded_app["status_token"], "status_token was not auto-generated on insert"


@pytest.mark.asyncio
async def test_status_portal_returns_timeline(seeded_app, client):
    """P1-8: status endpoint must surface a candidate-safe timeline + the
    pre_eval_token key (frontend renders both)."""
    r = await client.get(f"/api/v1/status/{seeded_app['status_token']}")
    assert r.status_code == 200, r.text
    body = r.json()
    assert "timeline" in body and "pre_eval_token" in body
    assert any(ev["event"] == "Application received" for ev in body["timeline"])
    assert body["pre_eval_token"] is None  # none created yet


@pytest.mark.asyncio
async def test_pre_evaluation_get_submit_and_surfaces_in_status(seeded_app, client, db_pool):
    """P1-7 + P1-8: pre-eval is fetchable + submittable by token, and its token
    surfaces in the status portal so the candidate can find the assessment."""
    token = "loop-preeval-token-123"
    questions = [{"question_id": "q1", "question": "Why this role?"}]
    async with db_pool.acquire() as conn:
        await conn.execute(
            "INSERT INTO pre_evaluations (org_id,application_id,candidate_id,position_id,status,token,questions) "
            "VALUES ($1,$2,$3,$4,'pending',$5,$6)",
            seeded_app["org"], seeded_app["app_id"], seeded_app["candidate"],
            seeded_app["position"], token, json.dumps(questions),
        )

    # GET by token returns the questions
    r = await client.get(f"/api/v1/pre-evaluations/{token}")
    assert r.status_code == 200, r.text
    assert len(r.json()["evaluation"]["questions"]) == 1

    # Status portal now exposes the pre_eval_token
    r = await client.get(f"/api/v1/status/{seeded_app['status_token']}")
    assert r.json()["pre_eval_token"] == token

    # Submit answers
    r = await client.post(
        "/api/v1/pre-evaluations/submit",
        json={"token": token, "answers": [{"question_id": "q1", "answer": "Because I love backends."}]},
    )
    assert r.status_code == 200, r.text
    assert r.json()["status"] == "success"

    # Re-submitting is rejected (single-use)
    r = await client.post(
        "/api/v1/pre-evaluations/submit",
        json={"token": token, "answers": [{"question_id": "q1", "answer": "again"}]},
    )
    assert r.status_code == 400
