"""
agents/state.py – AgentState TypedDict for LangGraph state machine.
Exactly as documented in docs/BACKEND_PLAN.md §6 and §14.
This is the single source of truth for all state flowing through the pipeline.
"""
from typing import Optional, TypedDict


class SkillItem(TypedDict, total=False):
    """A single skill suggestion from internal or market analysis."""
    skill: str
    source: str          # e.g., "Sr Backend Dev" or "Google"
    year: Optional[int]  # e.g., 2024
    selected: bool       # Whether user accepted this skill


class JDVariant(TypedDict, total=False):
    """One of 3 JD variants generated by the drafting node."""
    type: str            # "skill_focused" | "outcome_focused" | "hybrid"
    summary: str         # Brief description of this variant style
    content: str         # Full JD markdown content
    skills_count: int    # Number of skills listed
    tone: str            # e.g., "Technical", "Inspiring", "Modern"


class BiasIssue(TypedDict, total=False):
    """A single bias issue found in the JD."""
    phrase: str          # The problematic phrase
    suggestion: str      # Suggested replacement


class ChatMessage(TypedDict, total=False):
    """A single message in the chat history."""
    role: str            # "user" | "assistant" | "system"
    content: str
    extras: Optional[dict]  # Card data, metadata, etc.


class AgentState(TypedDict, total=False):
    """
    Complete LangGraph state for the recruiter chat JD generation pipeline.

    Pipeline: INTAKE → INTERNAL_CHECK → MARKET_RESEARCH → JD_VARIANTS → FINAL_JD → BIAS_CHECK → COMPLETE
    """

    # ── Session Identity ──────────────────────────────────────────
    session_id: str
    org_id: int
    department_id: Optional[int]
    user_id: int

    # ── Intake Data (gathered during conversation) ────────────────
    role_name: Optional[str]
    experience_min: Optional[int]
    experience_max: Optional[int]
    skills_required: list[str]
    location: Optional[str]
    work_type: Optional[str]           # "remote" | "hybrid" | "onsite"
    employment_type: Optional[str]     # "full_time" | "contract" | "internship"
    additional_requirements: Optional[str]

    # ── Internal Skills Check ─────────────────────────────────────
    internal_skills_found: list[SkillItem]
    internal_skills_accepted: list[str]
    internal_skipped: bool

    # ── Market Research ───────────────────────────────────────────
    market_skills_found: list[SkillItem]
    market_skills_accepted: list[str]
    market_skipped: bool
    competitors_used: list[str]

    # ── JD Variants ───────────────────────────────────────────────
    jd_variants: list[JDVariant]
    selected_variant: Optional[str]    # "skill_focused" | "outcome_focused" | "hybrid"

    # ── Final JD ──────────────────────────────────────────────────
    final_jd: Optional[str]            # Full markdown JD

    # ── Bias Check ────────────────────────────────────────────────
    bias_issues: list[BiasIssue]
    bias_skipped: bool

    # ── Workflow Control ──────────────────────────────────────────
    stage: str                         # Current pipeline stage
    messages: list[ChatMessage]        # Full chat history
    awaiting_user_input: bool          # True when paused for user action
    user_action: Optional[str]         # Last user action: "accept", "skip", "select_variant", "message"
    user_action_data: Optional[dict]   # Data for user action (e.g., selected skills, variant type)

    # ── Org Context (loaded on session start) ─────────────────────
    org_about_us: Optional[str]
    org_culture_keywords: Optional[str]
    org_benefits_text: Optional[str]

    # ── Error Recovery (per §14) ──────────────────────────────────
    error_stage: Optional[str]         # Which stage failed
    error_code: Optional[str]          # Machine-readable code
    error_message: Optional[str]       # Human-readable message
    retry_count: int                   # Consecutive retry count

    # ── Reference JD (uploaded file) ──────────────────────────────
    reference_jd_text: Optional[str]   # Extracted text from uploaded JD


def create_initial_state(
    session_id: str,
    org_id: int,
    user_id: int,
    department_id: Optional[int] = None,
) -> AgentState:
    """Create a fresh AgentState with all defaults set."""
    return AgentState(
        session_id=session_id,
        org_id=org_id,
        department_id=department_id,
        user_id=user_id,
        role_name=None,
        experience_min=None,
        experience_max=None,
        skills_required=[],
        location=None,
        work_type=None,
        employment_type=None,
        additional_requirements=None,
        internal_skills_found=[],
        internal_skills_accepted=[],
        internal_skipped=False,
        market_skills_found=[],
        market_skills_accepted=[],
        market_skipped=False,
        competitors_used=[],
        jd_variants=[],
        selected_variant=None,
        final_jd=None,
        bias_issues=[],
        bias_skipped=False,
        stage="intake",
        messages=[],
        awaiting_user_input=False,
        user_action=None,
        user_action_data=None,
        org_about_us=None,
        org_culture_keywords=None,
        org_benefits_text=None,
        error_stage=None,
        error_code=None,
        error_message=None,
        retry_count=0,
        reference_jd_text=None,
    )
